### ISSUE TITLE
vars.base unusable

### ISSUE THREAD

**Issue by Kaivela** [LiveSplit/LiveSplit.AutoSplitters#1418]
why `vars.base` can't be used in an autosplitter ?
I tested it with `vars.base1` and it works fine

**Comment by just-ero** [comment]
Presumably you have not created a variable called `vars.base`. This is impossible to know without being provided with any kinds of code samples and error messages.

Additionally, this is unrelated to this repository. Please direct your questions somewhere more appropriate, such as the [Speedrun Tool Development Discord server](https://discord.gg/N6wv8pW).
